# Generated by Django 5.2.1 on 2026-01-20 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_vyakaran', '0002_question_difficulty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning_vyakaran.lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning_vyakaran.quiz'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['lesson', 'order'], name='learning_vy_lesson__92284a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz', 'order'], name='learning_vy_quiz_id_395957_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('quiz__isnull', False), ('lesson__isnull', False), _connector='OR'), name='question_has_quiz_or_lesson'),
        ),
    ]
