# Generated by Django 5.2.1 on 2026-01-20 07:47

from django.db import migrations
import uuid


def migrate_exercises_to_questions(apps, schema_editor):
    """
    Migrate lesson exercises from JSON field to Question model records.
    """
    Lesson = apps.get_model('learning_vyakaran', 'Lesson')
    Question = apps.get_model('learning_vyakaran', 'Question')
    
    migrated_count = 0
    
    for lesson in Lesson.objects.all():
        exercises = lesson.exercises or []
        
        if not exercises:
            continue
        
        for idx, exercise in enumerate(exercises):
            # Transform options format from simple list to structured format
            options_data = []
            exercise_options = exercise.get('options', [])
            correct_answer_idx = exercise.get('correctAnswer', 0)
            
            for i, option_text in enumerate(exercise_options):
                options_data.append({
                    'text': option_text,
                    'text_nepali': option_text,
                    'is_correct': i == correct_answer_idx
                })
            
            # Create Question record
            try:
                Question.objects.create(
                    id=uuid.uuid4(),
                    lesson=lesson,
                    question_text=exercise.get('question', ''),
                    question_text_nepali=exercise.get('question', ''),
                    question_type='multiple_choice',
                    difficulty=lesson.difficulty,
                    options=options_data,
                    correct_answer={'index': correct_answer_idx},
                    order=idx,
                    is_active=True
                )
                migrated_count += 1
            except Exception as e:
                print(f"Error migrating exercise {idx} for lesson {lesson.id}: {e}")
    
    print(f"Successfully migrated {migrated_count} exercises to Question records")


def reverse_migration(apps, schema_editor):
    """
    Remove questions that were created from lesson exercises.
    """
    Question = apps.get_model('learning_vyakaran', 'Question')
    deleted_count = Question.objects.filter(lesson__isnull=False).count()
    Question.objects.filter(lesson__isnull=False).delete()
    print(f"Deleted {deleted_count} lesson questions")


class Migration(migrations.Migration):

    dependencies = [
        ('learning_vyakaran', '0003_alter_question_options_question_lesson_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_exercises_to_questions,
            reverse_migration
        ),
    ]
